INSERT INTO bulletin (seller_id, created_at, title, price, text, status)
VALUES (1, '2018-07-12 21:09:29',
        'Quo ad aperiam aut autem labore culpa. Ut velit cumque quo molestiae. Facere dolor quia quia non dolore et non. Dolor optio fuga nihil enim aut aut blanditiis. Dignissimos dolor velit explicabo ullam optio eum et animi.',
        102.00,
        'Consequatur sed aut quia aut consectetur est. Asperiores sed vel omnis. Omnis molestias explicabo ipsum nam qui quae ut. Laborum aspernatur deserunt non repellendus.',
        'CLOSE'),
       (2, '2020-08-08 23:05:23',
        'Est harum blanditiis doloribus. Sint expedita nulla iure enim. Vero repellendus ad dolor harum magnam omnis reprehenderit. Eum molestiae eos qui nihil molestiae repudiandae.',
        154.66,
        'Officia at non asperiores nihil. Aut dolorem explicabo autem doloribus totam incidunt ab. Adipisci iste quaerat possimus id velit voluptatem.',
        'CLOSE'),
       (3, '2018-12-11 05:25:24',
        'Nesciunt rerum eum possimus. Libero alias dolorem saepe aperiam non tempore quam commodi. Numquam vel asperiores aut eum itaque nihil.',
        72.78,
        'Repellendus ut sed quisquam pariatur quam. Et minus voluptas autem velit minus. Ut natus reprehenderit cumque vitae.',
        'CLOSE'),
       (4, '2019-07-31 07:15:11',
        'Sit recusandae repellat voluptates vitae. Repellendus corrupti inventore cum eius iste iste est eius. In aut natus rem quia. Rerum expedita hic vitae in. Quas inventore maxime eos ut qui rem.',
        10.81,
        'Aut quae ullam ab molestias quam eveniet. Officiis consequatur aut quia eum doloremque molestias. Ipsa officiis nobis labore quae consequatur. Possimus exercitationem qui eos quia eaque.',
        'CLOSE'),
       (5, '2018-04-29 18:30:49',
        'Libero iste maiores nobis nemo assumenda porro voluptas. Sunt accusantium aspernatur eaque ea quia eligendi sit. Magni doloribus est molestiae enim.',
        56.85,
        'Maiores maiores corrupti voluptatem deserunt ut rerum ipsa. Sed quis ab corporis est. Veniam consequuntur assumenda est non est qui in.',
        'OPEN'),
       (6, '2019-01-01 05:40:19',
        'Nesciunt sint illum iste sapiente enim. Ullam voluptatem minus optio dolores voluptates nostrum. Molestiae velit aspernatur minus harum quis eius optio.',
        158.94,
        'Magnam molestias nihil optio qui esse autem facilis id. Est voluptatem rem nihil praesentium minima minus. Sapiente quisquam voluptatibus dolores. Rerum vel perspiciatis quod voluptas ut quae.',
        'OPEN'),
       (7, '2020-08-08 02:34:42',
        'Repellat impedit et dolor porro. Rerum animi fugiat sit et atque voluptatem. Soluta dolore nulla non neque dolorem ut.',
        150.60, 'Aut eaque numquam aut iure similique placeat iure quae. Impedit pariatur vitae molestiae beatae.',
        'OPEN'),
       (8, '2020-11-04 05:09:01', 'Voluptas facilis maiores qui. Unde inventore autem porro dolore eos ut.', 163.29,
        'Voluptatem at qui occaecati nulla nemo quia fugit. Ex accusantium aut ipsam exercitationem officia. Laboriosam illo et impedit corrupti soluta qui labore rerum.',
        'CLOSE'),
       (9, '2018-11-06 04:48:38',
        'Molestiae sint dolorem ipsam delectus qui quaerat officia. Corporis quidem sapiente ea doloremque. Nisi aperiam animi dolore dolorum. Quidem in ad qui nisi voluptas repellendus ea.',
        184.68,
        'Libero cum iusto officia quasi non natus. Asperiores quod incidunt voluptatibus voluptatum dolor est. Atque pariatur ducimus numquam beatae voluptates magnam est.',
        'CLOSE'),
       (10, '2020-11-01 14:34:22', 'Qui optio est possimus provident. Dolores aut consequatur aliquam est nostrum.',
        97.81,
        'Inventore magnam ex dolorem rerum impedit. Molestiae dolorem laboriosam qui quia dolorem. Praesentium distinctio voluptate dolor deserunt repellendus nemo. Vitae sequi facilis itaque est quia.',
        'CLOSE'),
       (11, '2018-08-12 17:17:21',
        'Repellat ea porro minima. Esse laborum voluptatem rem et reiciendis fugit. Aliquid maiores eligendi facere reprehenderit temporibus. Nulla ex iusto deleniti sunt dolorem dolorem ut molestiae.',
        81.14,
        'Ut neque aspernatur soluta deserunt. Architecto voluptas quo aut ipsam ut. Ullam est nemo sit quam. Modi adipisci neque est ab.',
        'OPEN'),
       (12, '2020-10-14 02:33:40',
        'Blanditiis repellat quis at doloribus est quaerat et. Ipsa ducimus est excepturi molestias quis. Accusamus debitis qui iusto ad fugit eos.',
        117.70,
        'Sunt amet amet laboriosam et et. Aut debitis rem numquam ut impedit. Corporis explicabo non eos earum aut porro. In illum aut iste ad recusandae error dolorum. Omnis voluptatem quo qui quisquam.',
        'OPEN'),
       (13, '2020-08-04 17:10:48',
        'Dolorum ab quas aut molestiae et aliquam beatae ut. Hic voluptatem voluptatem blanditiis voluptatibus enim eius quos.',
        75.63,
        'Molestiae velit non sed esse dolorem accusantium molestias quia. Nihil aut ducimus quis dolorem quia rerum quidem.',
        'OPEN'),
       (14, '2020-03-20 09:37:34',
        'Ut placeat architecto ullam odit est. Exercitationem est ipsa itaque quis atque amet molestiae. Consequatur qui eum eius voluptas.',
        23.44, 'Laboriosam nihil voluptatibus consequatur et. Accusantium sequi saepe eveniet commodi.', 'OPEN'),
       (15, '2020-05-13 09:06:03',
        'Sint doloribus laboriosam quia omnis. Deleniti nisi repudiandae dolorum non rerum aperiam quibusdam. Iure quod et animi incidunt sint ipsa esse. Fugit error voluptatem culpa facilis ea.',
        129.36,
        'Aperiam accusamus accusamus et. Est consectetur nisi ipsa quisquam sint. Sed dignissimos sunt magni error est et assumenda. Officiis et quia delectus mollitia.',
        'OPEN'),
       (16, '2018-02-15 21:36:11',
        'Dolor facilis incidunt minima consequatur eius a. Facere animi qui dolores aut maxime. Quasi debitis pariatur velit sunt. Qui sit quia maxime aut quod minus excepturi.',
        94.23,
        'Accusantium suscipit sed aliquid eius quia et illum. Eum sapiente in illo. Officia qui eos sit beatae et.',
        'CLOSE'),
       (17, '2018-08-14 20:17:46',
        'Suscipit omnis eum sit rem quos ipsam molestiae. Similique incidunt beatae numquam autem dolorem nam et ut. Doloremque maxime qui voluptate eum iste quam magni eos. Atque saepe autem nam temporibus omnis earum sapiente.',
        174.79,
        'Eligendi voluptas eum sint tempora id. Culpa adipisci voluptas sed tenetur inventore. Maiores maxime magni dolores et ea ipsum enim.',
        'OPEN'),
       (18, '2019-09-05 14:28:13',
        'Aut autem accusantium necessitatibus qui sint consequatur corporis veniam. Inventore enim amet voluptatem sit alias nostrum. Nisi asperiores molestias voluptatem molestiae dolor necessitatibus reprehenderit quibusdam.',
        160.76, 'Et quia nemo minus. A ut et et necessitatibus totam dolorum. Qui ut incidunt ea eius ut non quo.',
        'OPEN'),
       (19, '2019-04-07 09:41:53',
        'Tempore iure recusandae aut tempora quod ut ipsa autem. Laboriosam voluptas sunt harum. Incidunt qui cum illo tenetur. Officia tempora et doloribus tempora eveniet pariatur.',
        55.40,
        'Rerum occaecati fugit adipisci aut ratione dolor amet ut. Modi qui aliquam eum explicabo at consectetur dolor. Asperiores quia nostrum numquam.',
        'OPEN'),
       (20, '2018-06-04 16:56:07',
        'Dicta quo similique est sunt. Voluptatem quaerat iste reprehenderit in esse. Sed aut perspiciatis voluptas labore voluptas eligendi recusandae et. Non molestias dicta consectetur fugit rerum ratione.',
        184.63,
        'At velit excepturi dolore commodi et inventore. Vitae et earum ipsa autem aut expedita. Nesciunt occaecati facilis est voluptas voluptas est.',
        'CLOSE'),
       (1, '2018-03-04 03:22:59',
        'Eos ratione magni molestias non. Facilis perspiciatis rerum cumque velit necessitatibus voluptatem ea. Perferendis est deserunt veniam rem occaecati facilis iure.',
        39.81, 'Libero ullam cumque aspernatur. Autem voluptate possimus esse. Sint nemo architecto fugiat laborum.',
        'OPEN'),
       (2, '2019-03-02 15:34:26',
        'Dolores pariatur autem autem eaque itaque nihil. Sapiente aliquam ut impedit dolores pariatur. Fugit sed molestiae facilis est est. Qui nulla molestias aliquam quae.',
        47.83,
        'Dolores voluptatum omnis facilis in. Molestias ducimus voluptates et culpa quo et. Nesciunt tenetur non doloremque illo neque facere.',
        'CLOSE'),
       (3, '2020-04-21 12:53:13', 'Mollitia error placeat ut corrupti. Quos eligendi libero deserunt ex quaerat ipsam.',
        188.30,
        'Eum quos et ratione eum. Sed ipsa quo optio temporibus rerum beatae odit. Et dolorem provident eum quidem.',
        'OPEN'),
       (4, '2020-02-20 06:50:21',
        'Quia quibusdam et consequatur error recusandae suscipit ipsa. Error quas quia porro eius. Dolores sit similique vitae voluptatem sequi aliquid numquam et. Quo deleniti placeat corrupti nihil.',
        128.50,
        'Corporis repellat quis quam veritatis. Rem ut magnam distinctio est et. Veritatis suscipit est sit quasi. Molestiae dolores et dicta et.',
        'CLOSE'),
       (5, '2020-08-01 14:46:07', 'Aut quo ipsa sint eos quibusdam voluptates. Id delectus ut sint et. Et et iste aut.',
        105.61, 'Impedit qui aut libero esse nulla voluptatibus. Blanditiis totam magni velit vitae.', 'CLOSE'),
       (6, '2020-11-19 14:34:47',
        'Nulla eos aliquid magni dolor blanditiis perspiciatis nihil. Vel tempore ut sit alias in est molestias. Itaque laudantium incidunt qui nihil voluptas.',
        199.57,
        'Animi qui neque rerum eveniet porro. Quo iure nihil qui reprehenderit rerum. Est corporis nobis omnis ipsa praesentium.',
        'OPEN'),
       (7, '2020-06-26 13:23:37',
        'Et quo numquam sit placeat aut. Eum sit incidunt ratione beatae ea eum dolores. Deserunt excepturi sint numquam quia. Maiores recusandae autem quia laborum dicta et numquam. Qui ut voluptatem quia ut id commodi.',
        83.30,
        'Et voluptas natus porro animi. Maxime voluptatem eos nisi sit asperiores totam. Est maiores quibusdam dolorum atque consectetur aut.',
        'CLOSE'),
       (8, '2020-01-30 22:07:36',
        'Enim et provident minus libero quaerat unde. Tempore excepturi inventore cum eveniet excepturi. Enim perferendis ut et et vitae velit sed eius.',
        78.00,
        'Similique sed id fugit libero aut nemo iusto. Dolorum eius officia et vitae saepe qui. Iste quas est eum est non. Amet minima molestiae architecto voluptas placeat.',
        'OPEN'),
       (9, '2020-07-13 13:30:35',
        'Omnis in quasi sapiente voluptates ut. Laborum aut quisquam tempora magnam sed. Doloremque aut molestiae tempore. Enim at quia expedita voluptates adipisci.',
        153.00,
        'Accusantium iure consequatur non nam repellat voluptatem dolore. Est voluptatem at provident numquam. Voluptates et ut dolorem velit sunt.',
        'CLOSE'),
       (10, '2020-10-25 21:36:57',
        'Quis qui omnis mollitia qui tempore. Eveniet non voluptatum voluptas quo. Rerum architecto qui deserunt id. Quam ut impedit commodi quis esse.',
        198.52,
        'Vel temporibus eos non pariatur tempore similique voluptate. Eaque dolorem expedita placeat distinctio non consequatur. Harum veniam aut dolore. Culpa eaque quo doloremque beatae in molestias.',
        'CLOSE'),
