INSERT INTO comment (author_id, bulletin_id, created_at, text)
VALUES (1, 1, '2018-09-20 20:21:49',
        'Quia inventore assumenda dicta voluptates placeat illo. Eligendi qui accusantium voluptas error. Dolor saepe fugit similique nam. Magnam totam non labore iure.'),
       (2, 2, '2018-01-27 14:57:47',
        'Omnis fuga sed neque dolores dolor maxime. Eos voluptatum ut inventore. Vel expedita est doloremque totam occaecati eaque distinctio.'),
       (3, 3, '2018-12-26 15:58:30',
        'In placeat quidem a ullam consequatur minus. Qui ducimus doloribus et atque modi.'),
       (4, 4, '2020-05-26 08:49:38',
        'Non labore eum ad velit odio sed. Molestiae et autem consequatur ab fugiat eligendi. Eum iste non est vero ut. Id itaque reiciendis rerum debitis.'),
       (5, 5, '2019-04-09 03:05:56',
        'Et quis dolorem accusantium consequatur cumque dolores et. Architecto alias libero nam ab officia eveniet. Iste nobis facilis nostrum esse sapiente.'),
       (6, 6, '2019-10-03 06:31:14',
        'Aspernatur iusto qui aut asperiores et. Soluta soluta quisquam voluptatem veniam. Dolore aut sed sapiente quam et.'),
       (7, 7, '2018-01-13 18:31:49',
        'Itaque rerum accusantium illum fugiat ipsam. Sequi et aperiam a vitae deleniti et autem. Ipsum ducimus velit aut esse. Occaecati minus et adipisci eius quis facilis. Qui natus illo ipsum consequatur.'),
       (8, 8, '2018-12-01 22:00:49',
        'Sapiente et saepe id. Debitis eos beatae ut quos. Et ex vitae est. Est et repellendus totam non aut eos veniam architecto.'),
       (9, 9, '2020-06-20 01:24:57',
        'Voluptatem cupiditate in aliquam explicabo pariatur labore earum. Delectus atque odio eum. Et ea quia voluptas voluptate.'),
       (10, 10, '2018-09-23 20:37:40',
        'Qui autem qui aut molestiae. Et id iure magni quis ipsam expedita. Vel illum tenetur sit.'),
       (11, 11, '2019-10-05 05:41:10',
        'Magnam temporibus doloribus minima vitae ab. Accusamus culpa deleniti omnis. Eius cum sit quasi ex ex magni illo. Placeat est quisquam ut.'),
       (12, 12, '2018-06-11 01:05:36',
        'Ab sed et repellendus odio quia ducimus blanditiis. Minus iste earum aliquid fugit consectetur magnam nostrum. Possimus omnis eligendi provident nesciunt et.'),
       (13, 13, '2019-06-20 01:16:33',
        'Ut dolorum ratione et mollitia. Voluptatem iure ut voluptatem. Maiores aut fugiat voluptates ut. Animi sapiente libero minima sequi quae suscipit.'),
       (14, 14, '2020-01-12 16:09:58',
        'Asperiores mollitia similique accusantium aut dolor molestiae enim aspernatur. Quia nihil in voluptatem. Voluptate dolorum aut dignissimos quis atque sed commodi.'),
       (15, 15, '2018-10-07 17:28:27',
        'Est consequatur excepturi tenetur quo quia tempora. Unde veniam fugiat dolorem aperiam nam est quia. Saepe nemo necessitatibus ea illum iure. Et consequatur dolore nisi.'),
       (16, 16, '2018-05-04 23:35:11',
        'Dolorem sunt maiores quo. Vero repellat natus a debitis. Rerum voluptatibus dolorem quae cum ad perspiciatis ipsa nihil. Sint aperiam non doloribus dignissimos enim a.'),
       (17, 17, '2019-12-09 09:43:13',
        'Ipsam tenetur voluptas dolore laborum. Voluptas est et ut ut vel dolorem ea eos. Molestiae provident molestias voluptas quae vitae.'),
       (18, 18, '2019-07-22 12:44:12',
        'Neque sed voluptatibus id itaque. Sit similique ad qui. Consequatur commodi ullam ut autem.'),
       (19, 19, '2019-12-25 11:17:15',
        'Consequatur culpa ab et. Sed totam nulla earum voluptate nesciunt eligendi perferendis. Eligendi ad cum ut quisquam velit ea eum. Consequatur qui modi et. Vero dolores recusandae repellat sed.'),
       (20, 20, '2019-01-08 11:00:49',
        'Voluptatem unde recusandae ut autem expedita. Libero est quo accusantium non autem fugit. Sed aut sint placeat veritatis.'),
       (1, 21, '2019-06-26 22:08:30',
        'Qui exercitationem accusantium nobis. Exercitationem accusamus officia earum molestiae placeat.'),
       (2, 22, '2017-12-04 03:06:35',
        'Illum libero harum sit aliquid. Officiis error dolor itaque provident maxime. Dolore accusantium sed est adipisci non maxime.'),
       (3, 23, '2020-09-16 15:03:31',
        'At ut ducimus animi praesentium quia. Et quia accusantium nostrum voluptas recusandae. Modi iure est minima veniam dolorum necessitatibus et. Impedit labore quae reprehenderit.'),
       (4, 24, '2019-07-06 01:16:09',
        'Et laborum ea quo et consequatur est quis. Et rem quis vel unde sequi ut. Nihil ullam voluptatum totam et reprehenderit consectetur nihil.'),
       (5, 25, '2020-06-03 12:09:39',
        'Aspernatur nobis nostrum excepturi aut quisquam quam temporibus. Nisi asperiores id consequuntur itaque ea et modi. Doloremque pariatur laborum vero ipsam molestias in voluptas.'),
       (6, 26, '2018-12-25 19:41:41',
        'Qui aperiam eum repellat quis omnis eos incidunt nam. Quis sed excepturi aut consequuntur. Dolorem fuga reprehenderit mollitia itaque voluptas. Est occaecati reiciendis laboriosam rem rerum et quasi.'),
       (7, 27, '2018-10-27 20:44:02',
        'Dolorem qui unde dolor doloremque. Delectus voluptatem sunt sed est consequatur. Accusantium corrupti at dolor numquam tempora. Dolor id libero et voluptatem mollitia aspernatur nisi incidunt.'),
       (8, 28, '2018-05-01 02:20:39',
        'Exercitationem nam ducimus pariatur quisquam quos non sit. Aut et libero aut deleniti non. In officiis corporis ullam sapiente aut.'),
       (9, 29, '2018-08-16 01:30:57',
        'Sed suscipit illo quia. Fuga optio dolorem quo sit commodi minus inventore. Placeat sunt eos pariatur facilis. Ea ut nam qui consequatur possimus voluptas vero et.'),
       (10, 30, '2018-09-15 11:48:58',
        'Aut voluptatibus rerum assumenda itaque non nostrum. Porro dolorem ullam et suscipit sunt qui alias. Tenetur asperiores aut pariatur sed est. Ea error quam aut eligendi non nobis ullam sunt.'),
       (11, 1, '2020-10-12 15:13:39',
        'Corporis est voluptas voluptatum consequatur et. Odit est odit exercitationem voluptates qui sapiente. Similique ut porro animi et blanditiis.'),
       (12, 2, '2019-11-05 12:20:32',
        'Praesentium pariatur voluptate eum sit qui optio eos. Et ratione ipsam rerum magni. Recusandae quibusdam reiciendis illo consequatur. Harum recusandae animi modi odit eaque.'),
       (13, 3, '2020-05-03 03:41:07',
        'Iusto et et non. Officiis exercitationem incidunt provident facilis. Tempora sed inventore voluptas quas accusamus. Dolore rerum inventore est mollitia optio qui.'),
       (14, 4, '2020-01-22 04:42:50',
        'Consequatur animi placeat et dolore impedit quia exercitationem voluptas. Possimus a cum non et. Vel sed molestias et in.'),
       (15, 5, '2018-11-20 20:04:35',
        'Cumque dolorum architecto illo. Minus sint exercitationem perspiciatis nostrum pariatur ex.'),
       (16, 6, '2019-05-21 05:43:52',
        'Non possimus quo illo ullam. Delectus ut ut quibusdam perferendis ipsa ea. Totam voluptas expedita voluptatibus ab placeat. Laudantium id et odit similique quas natus quae fugiat.'),
       (17, 7, '2019-02-10 08:32:32',
        'Voluptates eum debitis mollitia tenetur dolorem non officia. Eum ea ut dolores ut. Ut voluptatem expedita unde.'),
       (18, 8, '2019-12-20 17:39:18',
        'Aut aliquid quia quos quis. Qui commodi vitae cum explicabo nisi consequatur. Praesentium dolorem omnis autem reiciendis et placeat ipsa id.'),
       (19, 9, '2018-06-18 14:18:55',
        'Quae reprehenderit cumque labore quidem veniam animi hic. Eum qui eaque facere hic eius quo blanditiis sequi. Tempore magni eos possimus occaecati ea.'),
       (20, 10, '2020-02-07 05:01:57',
        'Dolorem aliquam corporis pariatur eum ipsam doloremque quia non. Nulla quia ipsum laborum qui enim. Et et nam eos neque. Impedit nihil ut vitae. Rerum sit sequi voluptatum unde.'),
       (1, 11, '2019-08-29 06:52:05',
        'Sapiente aut minima eum doloribus fugit ratione omnis. Quam aut aperiam eos laborum qui provident. Similique placeat ipsum quasi. Quia quam eligendi laudantium quia dolorem repudiandae.'),
       (2, 12, '2018-05-05 23:19:15',
        'Ipsam aliquid incidunt earum ut asperiores. Vel repellat perferendis blanditiis fuga nemo maiores ut. Porro et error et. Dignissimos est laudantium nam ut iure distinctio nesciunt quas.'),
       (3, 13, '2019-12-22 02:33:51',
        'Recusandae veritatis a officia atque. Aliquam eius facilis neque non vitae quidem minus. Vitae fuga sit ex quia ut.'),
       (4, 14, '2018-09-26 03:02:28',
        'Aliquam corporis quibusdam tempora sed. Facilis accusantium distinctio delectus consequatur explicabo harum placeat. Dicta a qui est at eum sit.'),
       (5, 15, '2020-02-28 07:59:17',
        'Assumenda sunt quo consequatur. Sit ea aspernatur et consequatur inventore. Molestias odit nemo cupiditate sint ipsam quos quia.'),
       (6, 16, '2018-05-20 06:27:07',
        'Cum iure et quae dolores qui voluptatem. Sit nihil iste doloribus repellendus earum vel aliquam. Adipisci ad praesentium quas ea ut. Culpa et ut culpa rerum non omnis aut alias.'),
       (7, 17, '2019-05-06 21:41:15',
        'Est quo facilis consectetur architecto qui. Nisi laborum hic est expedita corrupti numquam ipsam corrupti. Ullam error maxime repudiandae optio officiis impedit.'),
       (8, 18, '2018-08-28 16:15:47',
        'In voluptatem alias suscipit facere velit. Sunt explicabo et sed dolores nihil. Qui aut dolore eos dolor commodi. Ipsum et omnis qui recusandae sit.'),
       (9, 19, '2017-11-24 17:49:31',
        'Est odit quasi eos sit pariatur voluptatum nesciunt. Dolores non deleniti dicta est aut.'),
       (10, 20, '2018-03-10 06:37:02',
        'Nulla expedita mollitia corporis molestias ipsa. Voluptas pariatur optio possimus placeat corrupti. Voluptates quidem ea est consequatur aliquid.'),
       (11, 21, '2019-06-30 16:47:47',
        'Commodi dolores voluptas amet sed voluptatum ratione velit. Sit reprehenderit nulla deleniti est dolore et. Aspernatur totam vel officia. Ab fuga molestias ab beatae.'),
       (12, 22, '2019-08-23 09:32:00',
        'Eum voluptatem consectetur et architecto occaecati blanditiis et. Qui fugiat eos deserunt optio neque et. Consequatur ducimus voluptas eum rerum cupiditate.'),
       (13, 23, '2018-06-15 22:17:12',
        'Consequatur alias non dolores excepturi odio deserunt. Officiis autem est quam. Nam dignissimos dolore veniam tempora id. Consequatur tempora sunt non sed ea dolor sunt.'),
       (14, 24, '2018-05-10 00:33:51',
        'Et dolor culpa ut eius. Repellat et accusamus esse omnis. Eveniet voluptatem laudantium reprehenderit molestiae nostrum qui. Voluptatem quis voluptatem laboriosam.'),
       (15, 25, '2018-01-24 03:59:17',
        'Blanditiis culpa provident est odio. Rerum minima et numquam quia nam eius. Consequuntur non omnis blanditiis fuga excepturi aut quia. Iusto eum labore voluptas doloribus consequatur repellat nihil.'),
       (16, 26, '2019-07-27 13:47:25',
        'Quis consectetur maiores velit rerum. Asperiores eligendi quia nesciunt aspernatur excepturi dicta. Eveniet id beatae magni. Repellat quia fugiat dolores molestiae.'),
       (17, 27, '2018-07-13 09:06:23',
        'Hic modi consequatur velit natus eos aut quae. Quia consequatur mollitia laboriosam non illo et.'),
       (18, 28, '2018-04-01 05:55:28',
        'Maxime atque temporibus quibusdam repellat iure ex. Aut et ut exercitationem velit optio voluptatem iste. Consequuntur itaque molestiae explicabo voluptatem repellendus aut aut dolores.'),
       (19, 29, '2019-02-01 08:42:50', 'At blanditiis aliquam sit non. Vel quam a laudantium in.'),
       (20, 30, '2019-02-25 23:20:15',
        'Amet dolores quia voluptas sit dolores. Quam veritatis aliquam aut et quia illo doloribus. Vel alias autem modi quas cumque ratione.'),
       (1, 1, '2018-09-17 09:58:10',
        'Est et quos in quas laudantium. Laboriosam veritatis modi quae ut sed ea. Incidunt soluta et delectus itaque rerum velit a rem. Voluptatem soluta et soluta sed. Inventore quaerat laudantium et velit.'),
       (2, 2, '2018-04-18 06:32:18',
        'Ut qui sed eligendi eum nisi nemo. Enim vel dolor temporibus possimus eveniet. Saepe quos beatae quod tempora sed aut porro. Quod qui odio delectus. Quisquam dicta doloribus placeat laborum quod.'),
       (3, 3, '2018-07-30 13:44:39',
        'Non asperiores quod voluptas corrupti. Culpa laudantium numquam et qui aliquam. Laudantium dolor eaque doloremque modi quod voluptates. Et tempora repellendus vel sed debitis ut nihil.'),
       (4, 4, '2018-09-11 12:43:31',
        'Et aut sunt repellendus in. Ut cum maiores temporibus voluptates sit. Eum aperiam sapiente autem molestiae in.'),
       (5, 5, '2019-11-17 04:27:47',
        'Reiciendis autem eos et qui architecto non sint. Ad commodi molestiae dolorem voluptatem sit nemo. Vel illo fuga sapiente similique eos et.'),
       (6, 6, '2018-07-12 18:13:15',
        'At tenetur eum consequatur eos ea perspiciatis in quia. Sint minus consequuntur voluptatem eos assumenda suscipit doloremque provident. Quia aperiam neque doloribus ea.'),
       (7, 7, '2018-05-18 20:10:23',
        'Repellendus magnam et qui aut illo. Suscipit error dicta officiis nemo voluptate rerum eveniet sed. Architecto vel minima incidunt non asperiores amet ipsum.'),
       (8, 8, '2018-11-03 19:43:06',
        'Eius ut sit facere in blanditiis dolorem. Aliquam natus dolorem rerum voluptate. Modi enim et rerum. Nobis qui ut quod et doloremque repellendus minus. Pariatur consequuntur quas perferendis et ut.'),
       (9, 9, '2018-02-08 17:59:32',
        'Quia sed et ullam. Aliquam autem alias fugit aut molestiae inventore. Et temporibus iste ipsum error nam. Recusandae et sunt ratione sequi odit.'),
       (10, 10, '2018-08-14 03:36:51',
        'Aut quos reiciendis quibusdam autem quis. Repellat expedita eos aliquam pariatur voluptatem officiis. Itaque quasi iste possimus sed vero. Qui et repudiandae omnis quia voluptatibus quisquam quia.'),
       (11, 11, '2018-08-13 22:24:53',
        'Ut dignissimos corporis rerum quo. Consectetur nihil fugit molestiae minima tenetur perferendis nesciunt. Nostrum dicta neque vel qui explicabo est. Dolores doloribus voluptatibus sed explicabo.'),
       (12, 12, '2019-10-29 05:35:26',
        'Id omnis non sunt debitis ut et et rerum. Voluptatem in incidunt vero id quod. Recusandae inventore sed aliquam quis. Inventore et non delectus.'),
       (13, 13, '2018-03-29 00:49:55',
        'Ut eum eos est non ab. Et vitae voluptatibus nihil magni totam. Qui alias quas officiis quos ducimus temporibus.'),
       (14, 14, '2018-11-18 02:45:05',
        'Et ab quo nemo ut aut minus architecto. Qui commodi beatae possimus quae quidem. Quia velit sapiente nulla saepe sit reiciendis. Ad ducimus est voluptas quam aut.'),
       (15, 15, '2018-04-27 00:58:20',
        'Eos minima ad ea sit ut. Possimus earum ipsam possimus minima et. Sit inventore similique corporis impedit. Possimus saepe laborum provident.'),
       (16, 16, '2020-02-04 01:07:06',
        'Sed est corporis in occaecati. Dolorem provident suscipit blanditiis odit non. Eum accusamus rerum inventore adipisci ratione voluptatem.'),
       (17, 17, '2019-06-30 06:24:53',
        'Quod libero tempore voluptate veniam minus. Aut qui ex incidunt temporibus ea excepturi. Eum voluptas similique odio corrupti odit sint aut.'),
       (18, 18, '2020-08-13 09:09:48',
        'Dolorem enim voluptatum similique rerum aliquid. Consequuntur corrupti sunt libero qui perspiciatis dolorem. Quae culpa quis reprehenderit omnis.'),
       (19, 19, '2019-06-03 18:27:26',
        'In dolorum aut ut libero ipsum. Molestiae pariatur facere ut saepe qui ipsa tenetur. Nostrum iste aut quia suscipit.'),
       (20, 20, '2020-01-31 20:18:42',
        'Quis id quam earum earum et laborum. Facere sed molestiae distinctio. Laboriosam non necessitatibus et corrupti iste. Non repellat quos voluptas non.'),
       (1, 21, '2019-08-02 18:44:27',
        'Non rerum voluptates in iure quos quos. Quod totam et dolore omnis est eius sit. Quis dolorem sunt aperiam error. Sit cum harum id id quis.'),
       (2, 22, '2019-02-07 21:02:29',
        'Eum nostrum ex voluptatum praesentium nam id. Voluptatem sint vel et qui ex eaque. Est ut ex sit iusto. Distinctio non quasi ad asperiores amet impedit rem ut. Ab nihil quia et atque.'),
       (3, 23, '2017-11-23 15:05:56',
        'Veniam consequatur sit impedit minima doloribus alias. Dolor et quibusdam quibusdam unde. Et nesciunt est quo. Quas laudantium rerum tempore sed culpa nobis.'),
       (4, 24, '2019-04-17 06:00:25', 'Ut qui qui ipsam sed. Et sit eaque magni optio quis.'),
       (5, 25, '2018-11-07 18:25:36',
        'Dicta ullam aut optio libero est culpa. Est magni eum laudantium et. Asperiores soluta similique consequatur. Laboriosam deleniti quia quos ea quis.'),
       (6, 26, '2019-02-28 16:13:25',
        'Inventore est architecto voluptatem sequi necessitatibus doloremque est. Inventore at asperiores hic asperiores dolores neque atque. Eum deleniti nemo necessitatibus sunt sit.'),
       (7, 27, '2019-11-06 06:50:01',
        'Cum enim eum rerum placeat. Laborum quasi pariatur quam et. Sequi facere nisi omnis sit sit eligendi assumenda. Porro voluptatibus aut quidem fuga nobis veniam.'),
       (8, 28, '2019-09-29 01:35:25',
        'Et molestiae est harum maiores sed placeat. Autem aliquid dicta omnis facilis. Non suscipit eos impedit quod eos.'),
       (9, 29, '2018-01-15 05:45:54',
        'Autem soluta quasi optio. Et sint blanditiis deleniti architecto asperiores qui. Quia ut laudantium amet enim non. Neque et enim ratione officia totam fugit suscipit.'),
       (10, 30, '2018-01-01 20:04:45',
        'Molestias enim voluptatum et quisquam eum est quisquam et. Earum ad quia reiciendis porro neque. Nobis quidem sed sapiente ut recusandae consequatur. Assumenda dolor voluptas quia officiis.'),
       (11, 1, '2018-11-12 00:07:56',
        'Earum commodi ut et officiis sed laborum. Recusandae vero expedita natus illum. Necessitatibus sapiente qui magnam rem non sint.'),
       (12, 2, '2018-04-30 15:15:04',
        'Deleniti officiis enim quia sunt. Minima voluptatem velit eaque expedita sit. Molestiae sed blanditiis sit est sint libero rerum et. Eveniet doloremque commodi omnis quam temporibus non.'),
       (13, 3, '2020-09-23 17:07:47',
        'Ratione et omnis id quo velit necessitatibus. Ut possimus aspernatur saepe incidunt iure saepe maxime. Ut id perspiciatis voluptatem possimus voluptate sint necessitatibus sapiente.'),
       (14, 4, '2018-11-15 08:49:53',
        'Aut omnis non esse natus inventore dolorem. Labore nostrum et aut asperiores. Repellendus nisi quae est qui et veniam qui non.'),
       (15, 5, '2018-09-02 20:53:01',
        'Culpa sed aspernatur inventore similique voluptatum. Quos sit temporibus reiciendis voluptates at quibusdam. Et error adipisci repudiandae corporis aut eos quia.'),
       (16, 6, '2018-01-12 09:29:00',
        'Non quasi sapiente aut rerum voluptas delectus cum necessitatibus. Et quos eveniet error est. Et officiis qui beatae vel recusandae. Non voluptate eos saepe ad autem.'),
       (17, 7, '2018-04-18 15:19:58',
        'Ut laboriosam quasi eum. Ratione qui aut id. Voluptatum voluptatem fugiat perferendis asperiores. Qui aut facilis enim officiis vitae.'),
       (18, 8, '2019-12-24 08:19:29',
        'Quidem aut exercitationem totam molestiae officia ut ratione. Accusamus numquam autem quod unde sunt cum delectus ex. Dolore assumenda perspiciatis beatae occaecati beatae.'),
       (19, 9, '2017-12-01 22:24:04',
        'Sed necessitatibus perferendis magni aut. Quisquam velit et ipsum aliquid dolorum. Eligendi ex laudantium quod est.'),
       (20, 10, '2018-07-04 01:38:37',
        'Repudiandae nobis ut numquam. Placeat cumque qui similique. Non placeat nemo iste. Doloribus est fuga et doloribus sit.');
